[package]
name = "ergotree-ir"
version = "0.13.1"
license = "CC0-1.0"
authors = ["Denys Zadorozhnyi <denys@zadorozhnyi.com>"]
edition = "2018"
description = "ErgoTree IR, serialization"
repository = "https://github.com/ergoplatform/sigma-rust"
exclude = [
    "proptest-regressions/*"
]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
sigma-ser = { version = "^0.2.0", path = "../sigma-ser" }
sigma-util = { version = "^0.2.0", path = "../sigma-util" }
k256 = { version = "0.4.2", features = ["rand", "zeroize"] }
elliptic-curve = {version = "0.5.0", features = ["rand", "zeroize"]}
thiserror = "1"
rand = "0.7"
lazy_static = "1.4"
derive_more = "0.99"
impl-trait-for-tuples = "0.2.0"
proptest = {version = "1.0.0", optional = true }
proptest-derive = {version = "0.3.0", optional = true }
bs58 = "0.4.0"
base16 = "0.2.1"
num-bigint = "0.4.0"
# bounded-vec = { git = "https://github.com/ergoplatform/bounded-vec", rev="6726ac0" }
bounded-vec = { version = "^0.2.0" }
serde = { version = "1.0", features = ["derive"], optional = true }

[features]
default = ["json"]
json = ["serde"]
arbitrary = ["proptest", "proptest-derive"]

[dev-dependencies]
proptest = "1.0.0"
sigma-test-util = { version = "0.2.0", path = "../sigma-test-util" }

